### ISSUE TITLE
Major Update to Model utilizing Laravel's Eloquent

### ISSUE THREAD

**Issue by dakshhmehta** [tombenner/wp-mvc#114]
Its been great seeing framework emerging using WordPress. I was wondering if core team would be interested to see Laravel Eloquent's ORM to see ported for WP MVC framework as Model and Database handling layer?

Me and bunch of other friends can work on it if core team is open to accept that PR in future for WP MVC.

It will definitely  be major change and if interested, can we continue discussion to handle the backward compatibility. 

Sorry to open this discussion as Issue.

**Comment by helarqjsc** [comment]
One of the problems of doing that would be increased requirements for the PHP version. Currently, WordPress 3.2 and forwards requires only PHP 5.2.4, but Laravel requires PHP 5.4+, so Eloquent probably needs a pretty high version too. It's quite a big problem in my opinion, because a lot of people use WP on cheap hostings and that would make this project unusable for them.

**Comment by cyberscribe** [comment]
I recommend that we aim to keep consistent with the compatibility guidelines WordPress themselves adhere to. Recently, plugins were being declined that used namespaces, because more than 15% of WordPress sites are run on versions of PHP that do not support namespaces. So, if we are adhering to similar standards, this is probably not a viable option at this time to maintain backwards compatibility. I do appreciate the suggestion, though, and look forward to further contributions.
