### ISSUE TITLE
Is there a way to run a custom query within the model?

### ISSUE THREAD

**Issue by gkweb** [tombenner/wp-mvc#129]
Am I missing something or is there a way to run a custom query in the model itself? In the same way as would be done in CakePHP? 
ie: 

`$someModelData = $this->query("SELECT * FROM wp_users");`

Or run the `$this->SomeOtherModel->find()` within the model?

Or is it expected to fall back to the Wordpress way using $wpdb?

Cheers

**Comment by cyberscribe** [comment]
I have been using `global $wpdb` but would welcome a pull request for `$this->prepare()` and `$this->query()` that passes through to `$wpdb` (maybe with substitution of {prefix} on table names).

In the case of `$model->SomeOtherModel->find()` I have instead been creating classes that do not inherit MvcModel to use the data mapper pattern (instead of the active record approach in current models), and this works quite well.
