### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by NitinPrakash** [tombenner/wp-mvc#161]
After activating plugin in WORDPRESS Setup and running  command line code 

./wpmvc generate plugin VenueListing on UBUNTU 16 i am getting this error

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Database Error</title>

</head>
<body>
    <h1>Error establishing a database connection</h1>
</body>
</html>

**Comment by cyberscribe** [comment]
Your WordPress isn't set up correctly yet.

**Comment by kulikov-e-s** [comment]
What does it mean 'Your WordPress isn't setup correctly yet'? Wordpress has been set up and running

**Comment by hersoncruz** [comment]
+1, Wordpress site works perfectly, I'm getting this error when running:
`➜  plugins git:(dev) ./wp-mvc/wpmvc generate plugin MyPlugin`

**Comment by cyberscribe** [comment]
The error "Database Error / Error establishing a database connection" is the standard error displayed when a WordPress site is not able to connect to the database. Usually, it happens when the site is not yet set up with database credentials in wp-config.php. It can however happen at other times, and it sounds like this is the case here with the plugin generator (which needs to access the DB to create tables).

Unfortunately, I am not able to reproduce this in any of my current setups (i.e. the generator works fine and creates the plugin). Can you provide more detail on the setup? Or has anyone else experienced this who might be able to have a look at the underlying code?
