### ISSUE TITLE
Translate messages 

### ISSUE THREAD

**Issue by carlos-porras** [tombenner/wp-mvc#182]
How to configure message translation so that it is in Spanish

**Comment by polcodemichalkrawczyk** [comment]
Just use genuine wordpress https://developer.wordpress.org/reference/functions/esc_html__/ or https://developer.wordpress.org/reference/functions/esc_attr__/ 
and then just translate your plugin.
Here you have some instructions https://premium.wpmudev.org/blog/how-to-translate-a-wordpress-plugin/
instead of using Poedit you can use https://wordpress.org/plugins/loco-translate/
