### ISSUE TITLE
Issue with multisiting

### ISSUE THREAD

**Issue by a-girin** [tombenner/wp-mvc#183]
Hello. Your plugin is awesome. But we faced with a problem when using the plugin with the Wordpress multisiting. Apparently the problem is that the plugin does not work on none of the sites (except the first site in network).
Perhaps the reason is usage of get_options() function, to get the list of plugins, which depend on mvc.
Would be very grateful for the hint or solution. Thank you

**Comment by cyberscribe** [comment]
I use it on miltisite just fine, but you have to activate for each site (not network activate). Would welcome a pull request to make it work network activated...

**Comment by ngosselin-mn** [comment]
@cyberscribe 

Thanks for your feedback on this issue.  I have been looking into this issue with @a-girin today.  

Looks like a partial solution is to switch get_option() to get_site_option() and update_action() to update_site_action() in lots of the file.

That's only part of the solution however, since hooks need to also be in place for when a new site is added that it runs the initial setup for that particular blog, and deactivation similar as well. (could probably be put into sub methods that activate/deactivate call if multisite is enabled.

Some of the model stuff is having issues with wp_insert_post() as well.

If we do come up with a solution I will most definitely submit a PR.

**Comment by ngosselin-mn** [comment]
@cyberscribe 

I should have a PR for this at some point next week (just need to formalize and such), I have it working correctly at this point within our system.

Changes to the core are pretty minor, the calendar events example, gets a lot of overhauling.

Cheers.

**Comment by ngosselin-mn** [comment]
@cyberscribe 

added pull request #184 to handle this.
