### ISSUE TITLE
Save multiple values of a select field?

### ISSUE THREAD

**Issue by hanenboujemaa** [tombenner/wp-mvc#193]
Hi,
I try to edit a form contains multiple select choice 

<?php echo $this->form->input('heure_fermeture',  array('label' => 'Heure de fermeture ', 'style' => 'width: 160px;','placeholder'=>'HH:MM')); ?>
<?php echo $this->form->select('jours_ouvrables',  array('label' => 'Jours Ouvrables ','multiple'=>'multiple','options'=>array('1'=>'Lundi','2'=>'Mardi','3'=>'Mercredi'))); ?>

When i inspect the html code in the browser i have this :
for the first field named : 'heure_fermeture' : 
<input id="AgenceHeureFermeture" name="data[Agence][heure_fermeture]" type="text" value="19:30:00" style="width: 160px;" placeholder="HH:MM">

but for the select field i don't have data[Agence][jours_ouvrables']
<select multiple="multiple" name="jours_ouvrables">
<option value="1">Lundi</option>
<option value="2">Mardi</option>
<option value="3">Mercredi</option>
</select>

how can i set the attribut 'jours_ouvrables' of the model 'Agence' by the value of the field 'jours_ouvrables' ?

**Comment by polcodemichalkrawczyk** [comment]
First - there is a bug in form helper that stops you from using <select> with attribute 'multiple'. It simply does not accept array of values. My pull request https://github.com/tombenner/wp-mvc/pull/191 fixes this bug. For now you just could create a similar helper in your plugin with this bug fixed so you don't have to wait for merging my changes.
As for passing array of values - in the array than contains all <selects> settings use 'value' field instead of 'option' field.

**Comment by hanenboujemaa** [comment]
Thank you for your answer, in fact I could find another solution with jquery using a plugin for multiple select: http://wenzhixin.net.cn/p/multiple-select/docs/index.html
it works perfectly in add view but in the edit view, it needsa little development but it works perfectly.
