### ISSUE TITLE
Creating module via shell not working

### ISSUE THREAD

**Issue by trang1104** [tombenner/wp-mvc#214]
I've just installed wp-mvc and tried to create my first plugin via shell, but it didn't work, it won't create any plugin. I tried  with 2 approaches:

1. Using wpmvc with git bash: `$ wpmvc generate plugin MyPlugin`
It doesn't pop out any error at all, as if it worked successfully, but no plugin was created.

2. Using wpmvc.bat with cmd and git bash: `$ wpmvc.bat generate plugin MyPlugin1`
* On git bash, it displayed the following error:
`./wpmvc.bat: line 1: @echo: command not found`
`./wpmvc.bat: line 2: rem: command not found`
`./wpmvc.bat: line 3: rem: command not found`
`./wpmvc.bat: line 4: syntax error near unexpected token ('
./wpmvc.bat: line 4: for %%F in ("%0") do set mvc_core_path=%%~dpF'`

* On cmd it displayed nothing, just like using wpmvc.

Seems like this issue isn't well-known as people rarely got it, I wonder if there is something missing with my environment? I'm using windows 7 and XAMPP.

**Comment by Jlomaka** [comment]
Hello, I had the same problem found such a solution, the first is necessary and Windows 7 to put ways for what he would understand the PHP. I have such a way turned out:

D:\OSPanel\modules\php\PHP-7.1-x64;

To put this, you need to go to "Start" 
-> "Computer" (right mouse button) and click on "Properties" 
-> next in the sidebar select "Advanced System Settings" and at the bottom there will be a button "Environment Settings" 
-> go there and there you have to have PATH press "Edit" you have a long string open and at the end end add your path to your folder inside which lies php.exe, as in the above do not forget to put ; before the new recording, it is MORE! "reboot the computer" and if everything is done correctly, when you get with the command line (I think it's worth using the base one since I'm doing everything through it) and go to the folder with the plugin that is: wp-content\plugins\wp-mvc and run command:

wpmvc generate scaffold VenueListing Venue

sometimes I get triggered and this option:

./wpmvc generate scaffold VenueListing Venue

And all should work, at least at me after such way all has worked with hurray
