### ISSUE TITLE
How to get only the html present in the view?

### ISSUE THREAD

**Issue by learnercys** [tombenner/wp-mvc#216]
When I get an item, let's say something like this `curl -X GET localhost/model`, the result is given with Wordpress template wrapped over the view, is there any way to avoid that? I mean, I just want to get the html present in the view. 

This is what I'm looking for:

```
<div class="view-container">
  content for `model`
</div>
```

and instead I'm getting something like this

```
<html>
.... this is html present in wordpress template and I don't needed

<div class="view-container">
  content for `model`
</div>

</html>
```

Any help will be appreciated it, thanks.

**Comment by cyberscribe** [comment]
You have a variety of options to accomplish this, including using include/require on the template file itself and then calling die(). I also often allow a variable to be passed to the view to tell it to display RSS/XML/JSON instead of HTML. Again, the key is to just output the format/subset of data you want, and then die() before the parent function can include the default view (which includes being wrapped in the WordPress template).
