### ISSUE TITLE
To many error on WordPress 4.1

### ISSUE THREAD

**Issue by vafrcor** [tombenner/wp-mvc#54]
When I tried to activate this plugin, there are few error due to instance new Class depreceated

**Comment by prabhuchelladurai** [comment]
I am working in WordPress 4.1 and it works fine... :+1:  Could you be specific about the errors? what other plugins have you activated along with this? especially WPMVC? If possible attach a screen shot...

**Comment by prabhuchelladurai** [comment]
@vafrcor I guess you could have encountered errors/warnings of the following nature:

1. Warning: Creating default object from empty value in /srv/www/wordpress-default/wp-content/plugins/wp-mvc-master/core/controllers/mvc_controller.php on line 110


2. Warning: mysql_real_escape_string(): Access denied for user 'www-data'@'localhost' (using password: NO) in /srv/www/wordpress-default/wp-content/plugins/wp-mvc-master/core/models/mvc_database.php on line 34

If this is the case, try these:

For 1:
In mvc_controller.php of your WP MVC plugin,
in line no 109, replace 'new stdClass()' with 'false'.

For 2:
In mvc_database.php, in line no 34,
replace 'mysql_real_escape_string($string)' with 'esc_sql($string)'.

Good luck.

**Comment by aaroncymor** [comment]
Hi @prabhuchelladurai , thanks for giving a solution to those errors. I've been encountering that for a while now (since weeks ago) and you helped me solve my problem. My skills in PHP are just basic, and I'm just beginning to understand wordpress and wpmvc. Hopefully, WPMVC gets updated again as it was tapped 2 - 3 years ago.
