### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by damianoporta** [tombenner/wp-mvc#69]
Hello,
i am tring to run **events-calendar-example** but i get this error
```
[MVC] Fatal Error: To associate posts with Speaker, its table needs to have a column named "post_id" of type BIGINT(20). Please run the following SQL to add and index the column:
ALTER TABLE wp_speakers ADD COLUMN post_id BIGINT(20);
ALTER TABLE wp_speakers ADD INDEX (post_id);

Thrown on line 60 of /var/www/wordpress/wp-content/plugins/wp-mvc/core/models/mvc_model.php 
```

**Comment by cyberscribe** [comment]
Thanks, this should be resolved as of [a8fe163](https://github.com/cyberscribe/wp-mvc/commit/a8fe1631aa3f091c058aa6c62303c40bfee55188). Please try the latest version in the GitHub repository and re-activate the plugin. It should not produce any errors now.

**Comment by damianoporta** [comment]
@cyberscribe i get the same errors when i try to activate the plugin (events-calendar-example).

```
[MVC] Fatal Error: To associate posts with Speaker, its table needs to have a column named "post_id" of type BIGINT(20). Please run the following SQL to add and index the column:
ALTER TABLE wp_speakers ADD COLUMN post_id BIGINT(20);
ALTER TABLE wp_speakers ADD INDEX (post_id);

Thrown on line 60 of /var/www/wordpress/wp-content/plugins/wp-mvc-a8fe1631aa3f091c058aa6c62303c40bfee55188/core/models/mvc_model.php 
```

**Comment by cyberscribe** [comment]
Hi Damiano,

Unfortunately, because you activated the example earlier before it was
fixed, it has already created the tables without the post_id in them. You
will need to run `drop table wp_speakers` and `drop table wp_venues` before
re-activating the plugin to get the new version of the plug-in to load in
the tables that contain these columns and keys.
(Alternatively, of course, you can do what the error says and run `ALTER
TABLE wp_speakers ADD COLUMN post_id BIGINT(20);` and `ALTER TABLE
wp_speakers ADD INDEX (post_id);`, but you will need to do something
similar for wp_venues as well, because both tables associate to wp posts,
and neither of them had the columns or keys in the previous version of the
example.)

I hope that makes sense! Thanks for reporting this.
Best,
Robert
