### ISSUE TITLE
Ship with plugin

### ISSUE THREAD

**Issue by No3x** [tombenner/wp-mvc#86]
Hi there,
I was wondering if it is possible to ship this with my own plugin and use it as mvc library. At least what happens if another plugin also does so.. Or if this library is already installed as plugin.. I think it's not possible that easy? 
Do you have any experience with this?
**Update:** After some reading it seems like I base my plugin on this framework and don't use wp-mvc as library. I'm right?

**Comment by cyberscribe** [comment]
If you mean distribute on the WordPress Plugin Repository, that may not be so easy because it does not do any dependency management, and the wp-mvc plugin will be a required dependency for your plugin if you are developing it in the normal way. Other installation systems do specify prerequisites, so you might be able to distribute it along with e.g. a git pull of wp-mvc as a requirement. Hope that helps.
