### ISSUE TITLE
What do you think about adding namespace?

### ISSUE THREAD

**Issue by celorodovalho** [tombenner/wp-mvc#95]
I can start this work, but I need the comunity opinion before.

**Comment by cyberscribe** [comment]
Namespaces are generally discouraged in WordPress plugins because about 15% of all WP installations use a version of PHP that is too low to support namespaces.

Since wp-mvc is highly object-oriented, with only a few non-class-method functions, we achieve a similar separation of execution space in this way.

**Comment by celorodovalho** [comment]
Namespaces are the future of PHP... I mean is the present yet.

I was reading some articles about that:

http://www.paulund.co.uk/namespacing-autoloaders-wordpress-plugins
http://wordpress.stackexchange.com/questions/63668/autoloading-namespaces-in-wordpress-plugins-themes-can-it-work

**Comment by celorodovalho** [comment]
What do you think to re-think this idea now?
